In [2]:
import numpy as np;

In [3]:
a=np.array([1,2,6,7])

In [4]:
print(a+2)

[3 4 8 9]


In [5]:
print(a*3)

[ 3  6 18 21]


In [6]:
print(a/2)

[0.5 1.  3.  3.5]


In [7]:
a=[1,2,3,4,5,6,7,8]

In [8]:
reverse_arr=a[::-1]

In [9]:
print(reverse_arr)

[8, 7, 6, 5, 4, 3, 2, 1]


In [10]:
x=np.array([1,2,3,4,5,1,2,1,1,1])

In [11]:
values,count=np.unique(x,return_counts=True)

In [12]:
most_frequent=values[np.argmax(count)]

In [13]:
indices=np.where(x==most_frequent)[0]

In [14]:
print("Most frquent value is",most_frequent,"in index:")

Most frquent value is 1 in index:


In [15]:
print(indices)

[0 5 7 8 9]


In [16]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])

In [17]:
print(arr[0])

[10 20 30]


In [18]:
for i in range(0,3):
  print(arr[i][1])


20
50
80


In [19]:
print(arr[2])

[70 80 90]


In [20]:
for i in range(0,3):
  print(arr[i][0])

10
40
70


In [21]:
Shounok=np.linspace(10,100,25)

In [22]:
print(Shounok)

[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


In [23]:
print(Shounok.ndim)

1


In [24]:
print(Shounok.shape)

(25,)


In [25]:
print(Shounok.size)

25


In [26]:
print(Shounok.dtype)

float64


In [27]:
print(Shounok.nbytes)

200


In [28]:
print(Shounok.reshape(25,1))

[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


In [29]:
UCS420_Shounok=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])

In [30]:
Mean=np.mean(UCS420_Shounok)

In [31]:
print(Mean)

43.333333333333336


In [32]:
Median=np.median(UCS420_Shounok)

In [33]:
print(Median)

37.5


In [36]:
print("Maximum:", np.max(ucs420_yourname))
print("Minimum:", np.min(ucs420_yourname))
print("Unique Elements:", np.unique(ucs420_yourname))

NameError: name 'ucs420_yourname' is not defined

In [ ]:
reshaped_ucs420_yourname = ucs420_yourname.reshape(4, 3)

print("\nReshaped Array (4 x 3):")
print(reshaped_ucs420_yourname)

# Resize to 2 rows and 3 columns
resized_ucs420_yourname = np.resize(ucs420_yourname, (2, 3))

print("\nResized Array (2 x 3):")
print(resized_ucs420_yourname)